class GC9A01Display
  def self.configure: (Integer spi_host, Integer sclk, Integer mosi, Integer cs, Integer dc, Integer rst, Integer bl, Integer frequency) -> bool
  def self.configure_secondary: (Integer spi_host, Integer sclk, Integer mosi, Integer cs, Integer dc, Integer rst, Integer bl, Integer frequency) -> bool
end

class GC9A01Speedometer
  def initialize: (?Integer display_index) -> void
  def render: (Numeric speed_kmh, Numeric cadence_rpm, ?bool speed_connected, ?bool cadence_connected) -> Numeric
  def demo_step: () -> Numeric
  def demo: (?Integer frame_ms) -> bot
  def brightness=: (Integer value) -> Integer
  def initialized?: () -> bool
end

class GC9A01SimpleSpeedometer
  def initialize: (?Integer display_index) -> void
  def render: (Numeric speed_kmh) -> Numeric
  def demo_step: () -> Numeric
  def demo: (?Integer frame_ms) -> bot
  def brightness=: (Integer value) -> Integer
  def initialized?: () -> bool
end
